eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/henrysolo/SpringcloudConfig/
          searchPaths: respo
          username:
          password:
      label: master
  rabbitmq:
    host: 192.168.174.100
    username: solo
    password: 709933547
    port: 5672

management:
  security:
    enable: false